service: selenium-lambda

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  timeout: 900

functions:
  main:
    memorySize: 1000
    handler: handler.main
    events:
      - http:
          path: test
          method: get

    layers:
      - arn:aws:lambda:us-east-1:841529294410:layer:chromedriver:1
      - arn:aws:lambda:us-east-1:841529294410:layer:selenium:3

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        BinaryMediaTypes:
          - "*/*"